library:
    source-dirs: src
tests:
    learnyouahaskell-test:
        source-dirs: test
        main: Spec.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - learnyouahaskell
dependencies:
    - directory
    - base >= 4.7 && < 5
    - containers
    - directory
    - random
    - bytestring
name: learnyouahaskell
version: 0.1.0.0
extra-source-files:
    - README.md
    - ChangeLog.md
executables:
    learnyouahaskell-exe:
        source-dirs: app
        main: Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - learnyouahaskell
description: Please see the README
